### ISSUE TITLE
ctx.session is undefined when key in Redis was not found

### ISSUE THREAD

**Issue by justmavi** [telegraf/session#4]
### Desciption

Instead of creating a new key (as `telegraf-session-redis` does), `@telegraf/session/redis` does nothing. When a new user clicks on the Start button, it's clear that his key doesn't currently exist in the storage, and I get an exception when trying to access `ctx.session`. But when I create a key manually in Redis, everything works fine. But I can't create a key manually for each new user :(

Is this an issue or am I doing something wrong?

### Code

```js
import { session } from 'telegraf'
import { Redis } from '@telegraf/session/redis'

const opts = {
    host: process.env.REDIS_HOST ?? 'localhost',
    port: process.env.REDIS_PORT ?? 6379,
    db: process.env.REDIS_DB ?? 0,
}

const bot = new Telegraf(token, opts);
bot.use(session({ store: redisStore(opts) }));

const redisStore = (opts) => {
  let url = 'redis://';

  if (opts.username) {
    url += opts.username;

    if (opts.password) url += `:${opts.password}`;
    url += '@';
  }
  if (opts.host) url += opts.host;
  if (opts.port) url += `:${opts.port}`;
  if (opts.db) url += `/${opts.db}`;

  return Redis({ url });
};
```

### Current behavior

"TypeError: Cannot read properties of undefined (reading 'key')"

### Expected behavior

User's session

**Comment by MKRhere** [comment]
You should tell it what to default to:

```TS
bot.use(session({ store: redisStore(opts), defaultSession: () => ({}) }));
```

**Comment by justmavi** [comment]
Thank you for your answer. I'll try it a little later.
But if the problem is here, then it's better to update the documentation and specify it.

**Comment by justmavi** [comment]
That works. Thank you )
